<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.0.1 setup script
 * Date: Tue, 03 Mar 2020 10:53:59 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: aplus.czwbq18acehv.eu-west-3.rds.amazonaws.com [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'aplus-single.cirn0yz9dbnc.eu-west-3.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'carapau2020';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'j{/^d+=u.Ea4yS$)?K_>X6ZlpZ|;\\:OK';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>